[project]
name = "pyflink-workshop"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "apache-flink==2.2.0",
    "google-cloud-bigquery",
    "google-cloud-bigquery-storage",
    "google-cloud-storage",
    "google-auth",
]